import os
from typing import Optional
from dotenv import load_dotenv
from llama_index.core import Document, VectorStoreIndex, Settings

load_dotenv()

# Flag to track if LLM is initialized (lazy initialization to avoid startup errors)
_llm_initialized = False

def ensure_llm_initialized():
    """Lazy initialization of LLM settings - only called when needed."""
    global _llm_initialized
    
    if _llm_initialized:
        return
    
    # Gemini setup using .env file
    try:
        from llama_index.llms.google_genai import GoogleGenAI
        from llama_index.embeddings.google_genai import GoogleGenAIEmbedding
        
        key = os.getenv("GEMINI_API_KEY")
        if not key:
            raise ValueError("GEMINI_API_KEY not found in .env file")
        
        # Use gemini-2.5-flash (Jan 2025 - replaced 1.5-flash)
        Settings.llm = GoogleGenAI(model="gemini-2.5-flash", api_key=key)
        Settings.embed_model = GoogleGenAIEmbedding(model_name="text-embedding-004", api_key=key)
        _llm_initialized = True
        print("✅ Gemini LLM initialized from .env")
    except Exception as e:
        print(f"❌ LLM initialization failed: {e}")
        raise


# ============ Platform-Specific Prompt Templates ============

def get_blog_prompt(style_guide: str = None) -> str:
    """Full blog post with sections and headings (1000-2000 words)."""
    structure = """TASK: You are transforming a video transcript into a compelling blog post that reads like it was written by a human, not generated by AI.

CRITICAL RULES:
- Write as if you experienced this yourself or are telling a friend about it
- Use "I discovered...", "Here's what surprised me...", "The thing that stood out..."
- Include personal reactions and observations
- Avoid robotic phrases like "In this article", "Let's dive in", "In conclusion"
- Don't announce what you're about to say, just say it

STRUCTURE:
1. Hook (1-2 sentences that grab attention - a surprising fact, bold statement, or question)
2. Key Takeaways (3-5 bullet points of the most valuable insights)
3. Main content with H2 headings for each major topic
4. Wrap-up with a thought-provoking question or call-to-action

LENGTH: 1000-2000 words"""

    if style_guide:
        return f"""{structure}

--- YOUR UNIQUE VOICE ---
Channel this writing style throughout:
{style_guide}
Keep their specific expressions, energy level, and way of explaining things.
---"""
    return f"{structure}\n\nTONE: Conversational and engaging, like explaining to a smart friend."


def get_linkedin_prompt(length: str = "medium", style_guide: str = None) -> str:
    """LinkedIn post - professional but personal storytelling."""
    length_guide = {
        "short": "200-400 words (quick read, punchy insights)",
        "medium": "400-700 words (balanced depth with engagement)",
        "long": "700-1000 words (detailed story with multiple takeaways)"
    }
    
    word_count = length_guide.get(length, length_guide["medium"])
    
    base_prompt = f"""TASK: Transform this video transcript into a LinkedIn post that feels genuine and gets engagement.

CRITICAL RULES:
- Start with a HOOK in the first line (bold statement, surprising stat, or personal admission)
- Use short paragraphs (1-3 sentences max)
- Include line breaks for readability
- Add 2-4 relevant emojis (don't overdo it)
- End with a question that encourages comments
- NO hashtags in the middle - put 3-5 at the very end if needed

FORMAT PATTERN (follow this):
[Hook line - make them stop scrolling]

[Short personal context or story]

[Key insight 1]

[Key insight 2]

[Key insight 3 if needed]

[Question for engagement]

---
[Optional: 3-5 hashtags]

LENGTH: {word_count}

TONE: Professional yet personal. Like you're sharing a genuine insight with your network, not giving a lecture."""

    if style_guide:
        return f"""{base_prompt}

--- YOUR UNIQUE VOICE ---
{style_guide}
Maintain their energy and personality while keeping it LinkedIn-appropriate.
---"""
    return base_prompt


def get_twitter_prompt(tweet_type: str = "thread", style_guide: str = None) -> str:
    """Twitter/X content - punchy and hook-driven."""
    
    if tweet_type == "single":
        base_prompt = """TASK: Condense this video's main insight into ONE powerful tweet (280 characters max).

RULES:
- Lead with the most surprising or valuable insight
- Use punchy, direct language
- Optional: include 1-2 emojis
- Make every word count
- End with intrigue or a mini call-to-action
- NO hashtags unless absolutely crucial

EXAMPLES OF GREAT TWEETS:
"The best negotiation trick I learned: stay silent after they give you a number. Most people can't handle the awkwardness and sweeten the deal."

"Spent 3 years in a toxic job before realizing: they weren't going to change. I had to. Left and doubled my salary in 6 months."

OUTPUT: Just the tweet text, nothing else."""
    else:
        base_prompt = """TASK: Transform this video into a Twitter/X thread (5-10 tweets).

THREAD STRUCTURE:
1. HOOK tweet - most shocking/valuable insight (must make them click "Show more")
2. Context tweet - brief setup
3-8. Value tweets - one key point each
Final tweet - Takeaway + encourage RT/follow

RULES FOR EACH TWEET:
- Max 280 characters
- Start with a hook or transition
- One idea per tweet
- Use "🧵" emoji in first tweet to signal thread
- Number tweets (1/, 2/, etc.)
- Use line breaks within tweets for readability
- 1-2 emojis max per tweet
- End thread with a clear CTA

FORMAT:
1/ [Hook tweet]

2/ [Context/setup]

3/ [First key insight]
...and so on

TONE: Punchy, confident, slightly provocative. Like you're sharing secrets you've discovered."""

    if style_guide:
        return f"""{base_prompt}

--- YOUR UNIQUE VOICE ---
{style_guide}
Keep their energy and expressions, but adapted for Twitter's punchy style.
---"""
    return base_prompt


# ============ Main Generation Function ============

def generate_blog_from_transcript(
    transcription: str, 
    style_guide: str = None,
    output_format: str = "blog",
    output_option: str = None
) -> str:
    """
    Generate content from transcript with platform-specific formatting.
    
    Args:
        transcription: The video transcript text
        style_guide: Optional style guide for voice matching
        output_format: 'blog', 'linkedin', or 'twitter'
        output_option: For linkedin: 'short'/'medium'/'long'; For twitter: 'single'/'thread'
    """
    print(f"Generating {output_format} content...")
    
    # Ensure LLM is initialized (lazy initialization)
    ensure_llm_initialized()
    
    document = Document(text=transcription)
    index = VectorStoreIndex.from_documents([document])
    query_engine = index.as_query_engine()
    
    # Get platform-specific prompt
    if output_format == "linkedin":
        prompt = get_linkedin_prompt(output_option or "medium", style_guide)
    elif output_format == "twitter":
        prompt = get_twitter_prompt(output_option or "thread", style_guide)
    else:  # Default to blog
        prompt = get_blog_prompt(style_guide)
    
    if style_guide:
        print(f"Applying custom style guide...")
    
    print(f"Sending prompt to Gemini ({output_format})...")
    response = query_engine.query(prompt)
    print("Gemini has finished generating content.")
    
    return str(response)


if __name__ == "__main__":
    print("Reading the transcript Data...")
    with open("demo/surajmahto.txt",'r', encoding="utf-8") as f:
        transcript_data= f.read()
    print("Reading the style Data...")
    with open("demo/suraj_mahto_style.txt",'r', encoding="utf-8") as d:
        style_data= d.read()
    
    # Test blog generation
    data = generate_blog_from_transcript(transcript_data, style_data, "blog")
    with open("demo/final_blog1.txt","w",encoding="utf-8") as s:
        s.write(data)
    
    # Test LinkedIn generation
    linkedin_data = generate_blog_from_transcript(transcript_data, style_data, "linkedin", "medium")
    with open("demo/linkedin_post.txt","w",encoding="utf-8") as s:
        s.write(linkedin_data)
